//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExamDbEntities2 : DbContext
    {
        public ExamDbEntities2()
            : base("name=ExamDbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LibraryRegion> LibraryRegions { get; set; }
        public virtual DbSet<LibSex> LibSexes { get; set; }
        public virtual DbSet<VolunteerList> VolunteerLists { get; set; }
    }
}
