//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolunteerList
    {
        public int VolunteerId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> Brithdate { get; set; }
        public Nullable<int> sex_id { get; set; }
        public string region_code { get; set; }
    
        public virtual LibraryRegion LibraryRegion { get; set; }
        public virtual LibSex LibSex { get; set; }
    }
}
